# Generated by Django 4.1.7 on 2023-02-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woke', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db',
        ),
    ]
